javascripts: 
layout : disqus
disqus :
  short_name : wordsmythblog
livefyre :
  site_id : 12345
intensedebate :
  account : 123abc
facebook :
  appid : 123
  num_posts: 5
  width: 580
  colorscheme: light
