---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : lynn
production_url : http://blog.wordsmyth.org
root_folder: /blog/

rss:
  limit: 20
  
posts:
  permalink: /posts/:year-:month-:day-:title.html
  summary_lines: 5
  latest: 10

pages:
  permalink: 'pretty'
  
pagination:
  base_page: index.html
  per_page: 10
  
publish:
  host: www.site.com
  root: ~/blog
