title : Lynn's Little Treasures
tagline: 
author :
  name : Lynn O'Meara
  email : lynn@wordsmyth.org
  github : lynnfaraday
  twitter : 
  feedburner : 

navigation :
  - archive.html
  - tags.html
  - about.html
